dist: trusty
language: php
php:
- hhvm

sudo: false

cache:
  directories:
  - $HOME/.composer/cache

branches:
  only:
  - master
  - travis

before_install:
  - echo -e "machine github.com\n  login $GH_TOKEN" >> ~/.netrc

script:
- sh build.sh

after_success:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sh publish.sh; fi

env:
  global:
    secure: "VPHSsrJ5WSseZ+nxoQ4dVZDQxXNITU4EJQm2CCrwZFhsdGVqEUcPveG6bV7gx+LXwxxCO2eA92J2EfpzglksrYwbh55fFBTTxxBvmEHrjje6GlyDV4SaTaSY3pPOP+6yNJNQQQRugeH7etk90PthQ7JcviFHLmq2ixEscNeNyZQ="
