language: php
php:
- hhvm

sudo: false

cache:
  directories:
  - $HOME/.composer/cache

branches:
  only:
  #- posts
  - travis

before_install:
  - echo -e "machine github.com\n  login $GH_TOKEN" >> ~/.netrc

script:
- sh build.sh

after_success:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sh publish.sh; fi
