sculpin_theme:
  theme: broderboy/deadfish
  #theme: sculpin/bootstrap-3-blog-theme

sculpin_content_types:
  posts:
    permalink: :year/:month/:filename.html
  pages:
    singular_name: page
    type: path
    path: _pages
    layout: single
    permalink: :title.html

jb_tag_cloud:
    tag_permalink: /tags/:taxon/index.html
    tag_entity: Jb\Bundle\TagCloudBundle\Model\Tag
    tag_cloud_entity: Jb\Bundle\TagCloudBundle\Model\TagCloud
    max_number: 0
    strategies:
        - jb_sculpin.tag_cloud.strategy.alpha
        - jb_sculpin.tag_cloud.strategy.percent_size

timbroder_algolia:
    enabled: true # enable the indexation at the end of the generate task
    engine: algolia # change the engine (for now only indextank is supported)
    options:
        application_id: "AB2NSR9192"
        admin_api_key: "9151a628fb6b0f5e8fb544e82ca1cfb6"
        index: "dev_timbroder.com"
        clear_on_sync: 0