# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: Tim Broder
subtitle: Code. Comics. Crossfit
#url: http://timbroder.com
author: Tim Broder
email: timothy.broder@gmail.com
disqus_shortname: timbrodercom

# Insert your disqus shortname
disqus:
    shortname: broderboy